### ISSUE TITLE
[    ERROR] - global name 'cmd' is not defined

### ISSUE THREAD

**Issue by yongchao** [nugentechnologies/nudup#13]
Hi,

When I run the program, it complained that 

"[    ERROR] - global name 'cmd' is not defined"

This is due to the mistyped variable cmd at line 756 on the Dec 2, 2017 version of the file nudup.py

cmd.append("gzip -c -d")

Should be replaced by

cmds.append("gzip -c -d")

This bug probably only happens when a gzipped file is used.

**Comment by mlovci** [comment]
Thanks for reporting this. We have resolved this bug with #14.

**Comment by yongchao** [comment]
Thanks.
