### ISSUE TITLE
How to get index.fq file from bcl files?

### ISSUE THREAD

**Issue by YuanTian1991** [nugentechnologies/nudup#24]
Hi dear NuGEN tech team, I am new to analysing RRBS data, and currently stuck on the Nudup step. Since I can not find how to generate the index.fq file. Could you help me with that?

**Comment by mlovci** [comment]
Instructions for `bcl2fastq` are in Appendix F of the [RRBS user guide](https://www.nugen.com/sites/default/files/M01394_v6_User_Guide%3A_Ovation_RRBS_Methyl-Seq_System_5912.pdf)
